# None as otherwise it clobbers our compiler choce
language: cpp

# Ubuntu 16.04 Xenial support
sudo: required
dist: xenial

services:
  - docker

# Build
script:
  - docker run -v $PWD:/tmp/gerbera-src -w /tmp/build -e CXX=$CXX -e CC=$CC -e CXXFLAGS=$CXXFLAGS gerbera/gerbera-ci-base:latest bash -c "bash ../gerbera-src/scripts/install-googletest.sh && cmake ../gerbera-src -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_SYSTEMD=0 -DWITH_TESTS=1 && make install && make test"

env:
  - CXX=g++-7 CC=gcc-7
  - CXX=g++-8 CC=gcc-8
  - CXX=clang++-7 CC=clang-7 CXXFLAGS=-stdlib=libc++

jobs:
  include:
  - stage: Test Gerbera UI
    addons:
      chrome: stable
    before_install: skip
    install:
      - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web/ install $TRAVIS_BUILD_DIR/gerbera-web/
    script:
      - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web run lint
      - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web run test
      - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web run test:e2e
