name: lint-clang-format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: './src'
          exclude: './src/contrib'
          extensions: 'h,cc'
          clangFormatVersion: 18
