name: build-deb

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  deb-package:
    strategy:
      fail-fast: false
      matrix:
        os-ver: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:20.10" "ubuntu:21.04", "debian:stable", "debian:testing", "debian:unstable"]
    runs-on: ubuntu-latest
    container:
      image: "${{ matrix.os-ver }}"
      env:
        ART_API_KEY: ${{ secrets.ART_API_KEY }}
        DEBIAN_FRONTEND: noninteractive
        TZ: Etc/UTC
    steps:
      - name: Install script pre-reqs
        shell: bash
        run: |
          ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
          apt-get update -y
          apt-get install -y lsb-release sudo wget curl
          # Actions needs 2.18, Bionic has 2.17....
          if [[ $(lsb_release -c --short) == "bionic" ]]; then
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:git-core/ppa
            sudo apt-get update -y
          fi
          apt-get install -y git

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # We need history/tags to generate version info

      - name: Build and upload deb
        run: |
          bash scripts/debian/build-deb.sh

      - uses: frabert/replace-string-action@v1.2
        id: replace
        with:
          pattern: '(\w+):([\w\.]+)'
          string: ${{ matrix.os-ver }}
          replace-with: $1-$2.deb

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.replace.outputs.replaced }}
          path: build-deb/*.deb
