name: build-deb

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  deb-package:
    strategy:
      fail-fast: false
      matrix:
        os-ver: ["ubuntu:18.04", "ubuntu:20.04", "ubuntu:22.04", "ubuntu:22.10", "debian:stable", "debian:testing", "debian:unstable"]
        arch: ["linux/amd64", "linux/arm/v7", "linux/arm64/v8"]
        exclude:
          - os-ver: "ubuntu:18.04" # No Cmake backport for these versions
            arch: linux/arm/v7
          - os-ver: "ubuntu:18.04"
            arch: linux/arm64/v8
          - os-ver: "ubuntu:20.04" # CMake PPA broken: https://gitlab.kitware.com/cmake/cmake/-/issues/22683
            arch: linux/arm/v7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # We need history/tags to generate version info

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build and upload deb
        run: |
          docker run \
            --platform=${{ matrix.arch }} \
            -e TZ=Etc/UTC \
            -e ART_API_KEY=${{ secrets.ART_API_KEY }} \
            -e GITHUB_ACTIONS \
            -v "$(pwd):/build" \
            -w /build \
          ${{ matrix.os-ver }} \
          bash /build/scripts/debian/build-deb.sh ${{ matrix.os-ver }} ${{ matrix.arch }}

      - uses: frabert/replace-string-action@v1.2
        id: replace
        with:
          pattern: '(\w+):([\w\.]+):linux/(\w+)(?:/(\w+))?'
          string: '${{ matrix.os-ver }}:${{ matrix.arch }}'
          replace-with: $1-$2-$3$4.deb

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.replace.outputs.replaced }}
          path: build-deb/*.deb
